# -*- coding: utf-8 -*-
"""11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XC8HlZj-u_hDROthUC6YIyfATvD3_H_p
"""

input = """7232374314
8531113786
3411787828
5482241344
5856827742
7614532764
5311321758
1255116187
5821277714
2623834788""".splitlines()

example="""5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526""".splitlines()

#Part 1

lines = [[int(x) for x in r] for r in input]

flash = 0

for step in range(100):
  for r, line in enumerate(lines):
    for c, octo in enumerate(line):
      lines[r][c] += 1 

  while(True):
    finished = True
    for r, line in enumerate(lines):
      for c, octo in enumerate(line):
        if octo>9:
          finished = False
          lines[r][c] = -9
          right = len(line)-1
          bottom = len(lines)-1
          if bottom>r>0 and right>c>0:
            lines[r-1][c-1] += 1 
            lines[r+1][c+1] += 1  
            lines[r-1][c+1] += 1 
            lines[r+1][c-1] += 1  
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif r==0 and right>c>0:
            lines[r+1][c+1] += 1 
            lines[r+1][c-1] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom>r>0 and c==0:
            lines[r+1][c+1] += 1 
            lines[r-1][c+1] += 1  
            lines[r-1][c] += 1  
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom==r and right>c>0:
            lines[r-1][c-1] += 1 
            lines[r-1][c+1] += 1  
            lines[r-1][c] += 1  
            lines[r][c-1] += 1 
            lines[r][c+1] += 1 
          elif bottom>r>0 and right==c:
            lines[r-1][c-1] += 1 
            lines[r+1][c-1] += 1 
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
          elif r==0 and c==0:
            lines[r+1][c+1] += 1 
            lines[r+1][c] += 1  
            lines[r][c+1] += 1 
          elif bottom==r and c==0:
            lines[r-1][c+1] += 1 
            lines[r-1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom==r and right==c:
            lines[r-1][c-1] += 1 
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
          elif r==0 and right==c:
            lines[r+1][c-1] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1
    if finished:
      break
  count = 0
  for r, line in enumerate(lines):
    for c, octo in enumerate(line):
      if octo<0:
        count += 1
        flash += 1 
        lines[r][c] = 0
  
print(flash)
lines

#Part 2

lines = [[int(x) for x in r] for r in input]
flash = 0
step = 0
while(True):
  step += 1
  for r, line in enumerate(lines):
    for c, octo in enumerate(line):
      lines[r][c] += 1 

  while(True):
    finished = True
    for r, line in enumerate(lines):
      for c, octo in enumerate(line):
        if octo>9:
          finished = False
          lines[r][c] = -9
          right = len(line)-1
          bottom = len(lines)-1
          if bottom>r>0 and right>c>0:
            lines[r-1][c-1] += 1 
            lines[r+1][c+1] += 1  
            lines[r-1][c+1] += 1 
            lines[r+1][c-1] += 1  
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif r==0 and right>c>0:
            lines[r+1][c+1] += 1 
            lines[r+1][c-1] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom>r>0 and c==0:
            lines[r+1][c+1] += 1 
            lines[r-1][c+1] += 1  
            lines[r-1][c] += 1  
            lines[r+1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom==r and right>c>0:
            lines[r-1][c-1] += 1 
            lines[r-1][c+1] += 1  
            lines[r-1][c] += 1  
            lines[r][c-1] += 1 
            lines[r][c+1] += 1 
          elif bottom>r>0 and right==c:
            lines[r-1][c-1] += 1 
            lines[r+1][c-1] += 1 
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1 
          elif r==0 and c==0:
            lines[r+1][c+1] += 1 
            lines[r+1][c] += 1  
            lines[r][c+1] += 1 
          elif bottom==r and c==0:
            lines[r-1][c+1] += 1 
            lines[r-1][c] += 1 
            lines[r][c+1] += 1 
          elif bottom==r and right==c:
            lines[r-1][c-1] += 1 
            lines[r-1][c] += 1 
            lines[r][c-1] += 1 
          elif r==0 and right==c:
            lines[r+1][c-1] += 1 
            lines[r][c-1] += 1 
            lines[r+1][c] += 1
    if finished:
      break
  count = 0
  for r, line in enumerate(lines):
    for c, octo in enumerate(line):
      if octo<0:
        flash += 1
        count += 1
        lines[r][c] = 0
  
  if step==100:
    print("Part 1:", flash)
  if count>99:
    break

print("Part 2:", step)